parameters:
  pythonVersion: 3.7

jobs:
- job: Package

  pool:
    vmImage: ubuntu-16.04

  variables:
    python.version: ${{ parameters.pythonVersion }}

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install pip setuptools setuptools_scm wheel -U
    displayName: Install packaging utils

  - bash: |
      # This removes the +date local version component so it can be later uploaded to Azure Artifacts, PyPI, etc
      VERSION=`python -c 'import setuptools_scm; print(setuptools_scm.get_version(local_scheme=lambda v: ""))'`
      echo "##vso[task.setvariable variable=VERSION]$VERSION"
    displayName: Set VERSION variable

  - script: python setup.py sdist bdist_wheel
    displayName: Build sdist and wheel
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: $(VERSION)
  
  - task: PublishPipelineArtifact@0
    displayName: Publish artifacts
    inputs:
      artifactName: dist
      targetPath: dist