parameters:
  os: linux
  pythonVersions: [3.5, 3.6, 3.7]

jobs:
- job: ${{ format('Test_{0}', parameters.os) }}
  dependsOn: Package

  pool:
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: windows-2019

  strategy:
    matrix:
      ${{ each version in parameters.pythonVersions }}:
        ${{ version }}:
          os: ${{ parameters.os }}
          python.version: ${{ version }}

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python $(python.version)
    inputs:
      versionSpec: '$(python.version)'

  - task: DownloadPipelineArtifact@0
    displayName: Download artifacts
    inputs:
      artifactName: dist
      targetPath: dist

  - script: python -m pip install tox -U
    displayName: Install tox

  - bash: |
      WHEEL=`ls dist/*.whl`
      echo "##vso[task.setvariable variable=WHEEL]$WHEEL"
    displayName: Set WHEEL variable to current artifact

  - script: tox --installpkg $(WHEEL) --notest
    displayName: Provision tox environment

  - script: tox --installpkg $(WHEEL) --test-run-title="$(os) Python $(python.version)"
    displayName: Run tox tests
