jobs:
- template: .azure-pipelines/jobs/package.yml

- template: .azure-pipelines/jobs/test.yml
  parameters:
    os: linux
    pythonVersions: [3.6, 3.7]

- template: .azure-pipelines/jobs/test.yml
  parameters:
    os: windows
    pythonVersions: [3.6, 3.7]

- template: .azure-pipelines/jobs/publish.yml
  parameters:
    artifactFeed: bits
    dependsOn:
    - 'Test_linux'
    - 'Test_windows'
